# -*- coding: utf-8 -*-
"""Task-1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BkdrkZtEOeAQnpjtofFlViVSDYQo6OdW

## Task 1: Data Cleaning & Preprocessing

Objective: Learn how to clean and prepare raw data for ML.

Tools: Python, Pandas, NumPy, Matplotlib/Seaborn
"""

#Importing the dependencies
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import kagglehub

# Download latest version
path = kagglehub.dataset_download("yasserh/titanic-dataset")

print("Path to dataset files:", path)

#Imported Dataset
df = pd.read_csv(path+"/Titanic-Dataset.csv")
df.head()

df.info()

df.describe()

#Checking for the null-values
df.isnull().sum()

"""Observation:The Cabin feature as more number of null values."""

#Removing the not useful columns
df = df.drop(columns=['PassengerId','Name','Ticket','Cabin'],axis=1)

#Checking for the outliers in Age column
sns.boxplot(x=df['Age'])

#Removing the outliers in Age column
df.drop(df[df['Age']>70].index,inplace=True)

#Filling age column with the mean
df.fillna({'Age': df['Age'].mean()}, inplace=True)

#Boxplot for the Fare columns
sns.boxplot(x=df['Fare'])

#Removing the outliers in Fare columns
df.drop(df[df['Fare']>300].index,inplace=True)

df['Embarked'].value_counts()

df['Embarked'].mode()

df.fillna({'Embarked':'S'},inplace=True)

df.isnull().sum()

df.select_dtypes(include='object').columns

from sklearn.preprocessing import OneHotEncoder
one = OneHotEncoder()

df['Sex'] = one.fit_transform(df[['Sex']]).toarray()

df['Embarked'] = one.fit_transform(df[['Embarked']]).toarray()

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
df['Age'] = scaler.fit_transform(df[['Age']])
df['Fare'] = scaler.fit_transform(df[['Fare']])

df.head()

